package info.oais.archive.manager.service.format;

import info.oais.infomodel.structure.description.ChoiceDescription;
import info.oais.infomodel.structure.description.ElementDescription;
import info.oais.infomodel.structure.description.FieldDescription;
import info.oais.infomodel.structure.description.FormatDescription;
import info.oais.infomodel.structure.description.Occurrence;
import info.oais.infomodel.structure.description.PrimitiveType;
import info.oais.infomodel.structure.description.RecordDescription;
import info.oais.infomodel.structure.description.Semantics;
import info.oais.infomodel.structure.manifest.DescribedData;
import info.oais.infomodel.structure.manifest.ElementMeaning;
import info.oais.infomodel.structure.manifest.ManifestWriter;
import info.oais.infomodel.structure.manifest.StructureDescription;
import info.oais.infomodel.structure.manifest.ViewDescription;

import java.net.URI;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * What TOPCAT and SPLAT need to open data described in RepInfo Tools: a
 * table view of the description (which rows and columns to show, with each
 * column's units and meaning), and a Representation Information manifest
 * naming the data file, the structure descriptions -- DFDL and DRB SDF,
 * equivalent alternatives -- the table view, and what each element means.
 * Every file is named explicitly in the manifest; see oais-structure-manifest.
 *
 * <p>Kaitai Struct isn't offered: TOPCAT needs a class compiled from the
 * {@code .ksy} ahead of time, and Kaitai shows a repeated record as one array
 * where DFDL and DRB show same-named elements, so one table view can't serve
 * all three.</p>
 */
public final class ViewerBundle {

    private ViewerBundle() {
    }

    /**
     * The table view for {@code format}: its rows are the first repeated
     * record directly in the root (e.g. one reading per row), else the root
     * itself (one row); its columns are that record's fields that occur once,
     * with their types, units and meanings. Null if there's nothing to show.
     */
    public static String tableView(FormatDescription format) {
        RecordDescription rowRecord = null;
        for (ElementDescription e : format.root().children()) {
            if (e instanceof RecordDescription r && (r.occurrence() instanceof Occurrence.Repeated
                    || r.occurrence() instanceof Occurrence.UntilEnd)) {
                rowRecord = r;
                break;
            }
        }
        RecordDescription source = rowRecord != null ? rowRecord : format.root();
        StringBuilder columns = new StringBuilder();
        for (ElementDescription e : source.children()) {
            if (!(e instanceof FieldDescription f) || f.occurrence() instanceof Occurrence.Repeated
                    || f.occurrence() instanceof Occurrence.UntilEnd) {
                continue;
            }
            String type = columnType(f.type());
            if (type == null) {
                continue;
            }
            Semantics s = f.semantics();
            columns.append("        <column name=\"").append(xml(f.name())).append("\" type=\"").append(type).append('"');
            if (s.units() != null) {
                columns.append(" unit=\"").append(xml(s.units())).append('"');
            }
            String description = description(s);
            if (description != null) {
                columns.append(" description=\"").append(xml(description)).append('"');
            }
            columns.append("/>\n");
        }
        if (columns.isEmpty()) {
            return null;
        }
        String rows = rowRecord != null ? "<rows select=\"children\" name=\"" + xml(rowRecord.name()) + "\"/>"
                : "<rows select=\"self\"/>";
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <!--
                  How to view "%s" as a table, generated by archive-manager's RepInfo Tools:
                  %s Written for the tree DFDL and DRB decode it into. See
                  oais-structure-api's TableViewSpecificationReader for the format.
                -->
                <tableView>
                    %s
                    <columns>
                %s    </columns>
                </tableView>
                """.formatted(xmlComment(format.name()), rowRecord != null
                        ? "one row per \"" + xmlComment(rowRecord.name()) + "\" record, its fields as columns."
                        : "one row, the file's fields as columns.", rows, columns);
    }

    /**
     * The files of a bundle for TOPCAT and SPLAT, by file name: the manifest,
     * the DFDL and DRB SDF descriptions (whichever are given), the table view,
     * and a short README. Null if there's no table view or no description.
     *
     * @param dataFile the data file's name, as it will sit next to the manifest
     */
    public static Map<String, String> files(FormatDescription format, String baseName, String dataFile, String dfdl,
                                            String drbSdf) {
        String view = tableView(format);
        if (view == null || (dfdl == null && drbSdf == null)) {
            return null;
        }
        Map<String, String> files = new LinkedHashMap<>();
        List<StructureDescription> structures = new ArrayList<>();
        if (dfdl != null) {
            files.put(baseName + ".dfdl.xsd", dfdl);
            structures.add(new StructureDescription(null, StructureDescription.DFDL, URI.create(baseName + ".dfdl.xsd"),
                    null));
        }
        if (drbSdf != null) {
            files.put(baseName + ".drb.xsd", drbSdf);
            structures.add(new StructureDescription(null, StructureDescription.DRB_SDF,
                    URI.create(baseName + ".drb.xsd"), null));
        }
        files.put(baseName + "-table-view.xml", view);
        String self = "#" + baseName;
        DescribedData data = new DescribedData(self, format.name(), URI.create(encodePathSegment(dataFile)), structures,
                List.of(new ViewDescription(null, ViewDescription.TABLE, URI.create(baseName + "-table-view.xml"))),
                meanings(format));
        String manifest = ManifestWriter.write(format.name() + ": Representation Information for TOPCAT and SPLAT",
                List.of(data));
        files.put(baseName + ".ttl", manifest);
        files.put("README.txt", """
                %s -- Representation Information for TOPCAT and SPLAT
                (generated by archive-manager's RepInfo Tools)

                %s.ttl is a Representation Information manifest: it names the data file
                (%s -- put it in this folder, or edit the manifest to point elsewhere), the
                structure descriptions (%s: either will do), the table view, and what each
                element means. Every file is named in the manifest; rename or move them
                by editing it.

                TOPCAT, with oais-structure-topcat on its classpath:
                    java -Dstartable.readers=info.oais.infomodel.structure.topcat.OaisStructureTableBuilder \\
                         -cp "topcat-full.jar:oais-structure-topcat.jar:dependency/*" \\
                         uk.ac.starlink.topcat.Driver -f OAIS-RepInfo %s.ttl

                SPLAT, with oais-structure-splat on its classpath:
                    java -cp "oais-structure-splat.jar:dependency/*" \\
                         info.oais.infomodel.structure.splat.OaisStructureSpectrumLauncher %s.ttl
                """.formatted(format.name(), baseName, dataFile,
                String.join(" or ", structures.stream().map(StructureDescription::language).toList()), baseName,
                baseName));
        return files;
    }

    /** What each element means, by structural path ({@code record.field}), as the archive also records it. */
    static List<ElementMeaning> meanings(FormatDescription format) {
        List<ElementMeaning> meanings = new ArrayList<>();
        for (ElementDescription e : format.root().children()) {
            addMeanings(e, "", meanings);
        }
        return meanings;
    }

    private static void addMeanings(ElementDescription e, String parent, List<ElementMeaning> meanings) {
        String path = parent.isEmpty() ? e.name() : parent + "." + e.name();
        Semantics s = e.semantics();
        if (!s.isEmpty()) {
            meanings.add(new ElementMeaning(path, s.semanticName(), s.definition(), s.units(),
                    s.conceptUri() == null ? null : s.conceptUri().toString()));
        }
        if (e instanceof RecordDescription r) {
            r.children().forEach(c -> addMeanings(c, path, meanings));
        } else if (e instanceof ChoiceDescription c) {
            c.branches().forEach(b -> addMeanings(b.record(), path, meanings));
        }
    }

    private static String description(Semantics s) {
        if (s.semanticName() != null && s.definition() != null) {
            return s.semanticName() + ": " + s.definition();
        }
        return s.semanticName() != null ? s.semanticName() : s.definition();
    }

    /** The table view type for a field's values; null for raw bytes, which a table can't usefully show. */
    static String columnType(PrimitiveType type) {
        return switch (type) {
            case INT8, UINT8, INT16, UINT16, INT32 -> "int";
            case UINT32, INT64, BITS -> "long";
            case UINT64 -> "biginteger";
            case FLOAT32 -> "float";
            case FLOAT64 -> "double";
            case STRING -> "string";
            default -> null;
        };
    }

    private static String encodePathSegment(String name) {
        StringBuilder sb = new StringBuilder();
        for (byte b : name.getBytes(java.nio.charset.StandardCharsets.UTF_8)) {
            char c = (char) (b & 0xFF);
            if (Character.isLetterOrDigit(c) && c < 128 || "-._~".indexOf(c) >= 0) {
                sb.append(c);
            } else {
                sb.append('%').append(String.format("%02X", b & 0xFF));
            }
        }
        return sb.toString();
    }

    private static String xml(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;");
    }

    private static String xmlComment(String s) {
        return s.replace("--", "- -");
    }
}
