package info.oais.infomodel.structure.kaitai;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.Optional;

import org.junit.jupiter.api.Test;

import io.kaitai.struct.ByteBufferKaitaiStream;

import info.oais.infomodel.structure.ByteRange;
import info.oais.infomodel.structure.StructureNode;
import info.oais.infomodel.implementation.DigitalObjectRefImpl;
import info.oais.infomodel.structure.kaitai.generated.CsvPoints;
import info.oais.infomodel.structure.kaitai.generated.Point2d;

/**
 * Exercises {@link KaitaiReflectiveStructureNode#getSourceRange()} against
 * {@code generated/Point2d.java} and {@code generated/CsvPoints.java}, both
 * generated by the real Kaitai Struct compiler 0.11 with {@code --debug}
 * (see {@code src/main/ksy}), which record byte positions in their
 * {@code _attrStart}/{@code _attrEnd}/{@code _arrStart}/{@code _arrEnd} maps.
 */
class KaitaiReflectiveStructureNodeSourceRangeTest {

	@Test
	void reportsPerFieldByteRangesFromTheDebugMaps() {
		byte[] bytes = buildPointRecord(7, -3, "hi");
		Point2d point = new Point2d(new ByteBufferKaitaiStream(bytes));
		point._read(); // a --debug build doesn't parse in its constructor
		StructureNode root = KaitaiReflectiveStructureNode.ofRoot("point", point);

		ByteRange xRange = expectRange(root, "x");
		assertEquals(0, xRange.startByteOffset());
		assertEquals(4, xRange.byteLength());

		ByteRange yRange = expectRange(root, "y");
		assertEquals(4, yRange.startByteOffset());
		assertEquals(4, yRange.byteLength());

		ByteRange labelLenRange = expectRange(root, "labelLen");
		assertEquals(8, labelLenRange.startByteOffset());
		assertEquals(1, labelLenRange.byteLength());

		ByteRange labelRange = expectRange(root, "label");
		assertEquals(9, labelRange.startByteOffset());
		assertEquals(2, labelRange.byteLength());

		// The root itself has no enclosing _debug entry describing its own span -
		// see KaitaiReflectiveStructureNode's Javadoc for why that is left empty.
		assertTrue(root.getSourceRange().isEmpty());
	}

	@Test
	void reportsEachRepeatedRowsRangeAndTheirFieldsThroughTheAdapter() {
		byte[] bytes = "42,-7,hi\n7,13,demo\n".getBytes(StandardCharsets.US_ASCII);

		StructureNode csv = new KaitaiStructureRepInfo(new KaitaiFormatSpecification(CsvPoints.class))
				.apply(new DigitalObjectRefImpl(new ByteArrayInputStream(bytes)));

		StructureNode rows = csv.child("rows").orElseThrow();
		assertEquals(ByteRange.ofBytes(0, 19), rows.getSourceRange().orElseThrow());
		StructureNode second = rows.getChildren().get(1);
		assertEquals(ByteRange.ofBytes(9, 10), second.getSourceRange().orElseThrow());
		assertEquals(ByteRange.ofBytes(9, 2), expectRange(second, "x"));
		assertEquals("demo", second.valueAt("label").orElseThrow());
	}

	private static ByteRange expectRange(StructureNode root, String childName) {
		Optional<StructureNode> child = root.child(childName);
		assertTrue(child.isPresent(), () -> "expected a child named " + childName);
		Optional<ByteRange> range = child.get().getSourceRange();
		assertTrue(range.isPresent(), () -> childName + " should have a source range");
		return range.get();
	}

	private static byte[] buildPointRecord(int x, int y, String label) {
		byte[] labelBytes = label.getBytes(StandardCharsets.US_ASCII);
		ByteBuffer buffer = ByteBuffer.allocate(4 + 4 + 1 + labelBytes.length);
		buffer.putInt(x);
		buffer.putInt(y);
		buffer.put((byte) labelBytes.length);
		buffer.put(labelBytes);
		return buffer.array();
	}
}
