"""
drb-python driver generated by archive-manager's RepInfo Tools.

The driver is this generic interpreter plus DESCRIPTION (below): the format's
engine-neutral description - records, fields, choices, repetition, computed
lengths and counts, delimited text - as plain data, walked at read time. No
part of the description is ever executed as Python code; expressions are
small trees evaluated by _eval.

Each decoded element becomes a DrbNode, in data order. Repeated elements are
same-named siblings; a choice is a node holding the chosen branch's record;
an optional element whose condition is false is simply absent. Every node's
attributes carry its byte "offset" and "length", and its semantics
("semantic_name", "definition", "units", "units_uri", "concept_uri"); a coded
value also gets its "meaning", and a scaled value its "physical_value".

Four drb-python add-ons (the "drb.addon" entry points) give a decoded file's
meaning as a whole, and write it back - see _semantics, _metadata, _checks and
_write below. Each is registered as "<ADDON_PREFIX>_<kind>" and applies to
nodes of this driver's topic:

    node.get_impl(list, ADDON_PREFIX + "_semantics")  # every value, with its meaning
    node.get_impl(dict, ADDON_PREFIX + "_metadata")   # name -> value
    node.get_impl(list, ADDON_PREFIX + "_checks")     # problems found, if any
    node.get_impl(bytes, ADDON_PREFIX + "_write", changes={"/header/count": "3"})
                                                      # the file written back, with changes

A hand-written add-in - a module "addin" next to this one - can plug code into
the driver for what the description can't say. Every hook is optional:

    prepare(data: bytes) -> bytes   before decoding: decrypt, decompress, ...
    check(root) -> list of str      after decoding: checksums, CRCs, ...
    metadata(root) -> dict          more metadata, merged into _metadata's
    restore(data: bytes) -> bytes   when writing back: undo prepare(), e.g. encrypt

"root" is the decoded file; root.original_bytes are the file's bytes and
root.decoded_bytes what prepare() returned (the bytes the description read).
See the package's README.md for installing and using it.
"""
import importlib
import importlib.util
import io
import re
import struct
from decimal import Decimal
from typing import Any, Dict, List, Optional, Tuple

from drb.core import DrbFactory, DrbNode
from drb.exceptions.core import DrbFactoryException
from drb.nodes.abstract_node import AbstractNode
from drb.nodes.logical_node import WrappedNode

try:
    from drb.addons.addon import Addon
except ImportError:  # a drb without add-ons: they're still attached to decoded files
    Addon = object

_STRUCT = {"int8": "b", "uint8": "B", "int16": "h", "uint16": "H",
           "int32": "i", "uint32": "I", "int64": "q", "uint64": "Q",
           "float32": "f", "float64": "d"}
_WIDTH = {"int8": 1, "uint8": 1, "int16": 2, "uint16": 2, "int32": 4, "uint32": 4,
          "int64": 8, "uint64": 8, "float32": 4, "float64": 8}


class _Node(AbstractNode):
    """One decoded element: a value (field) or a group of nodes (record, choice)."""

    def __init__(self, name: str, value: Any, children: Optional[List[DrbNode]], attributes: Dict[str, Any]):
        super().__init__()
        self.name = name
        self.value = value
        self._children = children if children is not None else []
        for child in self._children:
            child.parent = self
        self._attrs = {(key, None): val for key, val in attributes.items() if val is not None}

    @property
    def attributes(self) -> Dict[Tuple[str, str], Any]:
        return self._attrs

    @property
    def children(self) -> List[DrbNode]:
        return self._children

    def __setitem__(self, key, value):
        raise NotImplementedError

    def __delitem__(self, key):
        raise NotImplementedError


class _Scope:
    """Values of fields read so far, looked up nearest record first - the same
    rule the description's expressions were validated against."""

    def __init__(self, parent: Optional["_Scope"]):
        self.parent = parent
        self.values: Dict[str, Any] = {}

    def lookup(self, name: str) -> Any:
        # A dotted name (header.length) is a field inside a record read earlier, which keeps its values by name.
        first, *rest = name.split(".")
        scope = self
        while scope is not None:
            if first in scope.values:
                value = scope.values[first]
                for part in rest:
                    value = value.values[part]
                return value
            scope = scope.parent
        raise ValueError(f"no value for {name!r} yet")


def _eval(expr: list, scope: _Scope) -> Any:
    kind = expr[0]
    if kind in ("int", "str"):
        return expr[1]
    if kind == "ref":
        return scope.lookup(expr[1])
    if kind == "neg":
        return -_eval(expr[1], scope)
    if kind == "not":
        return not _eval(expr[1], scope)
    op, left = expr[1], _eval(expr[2], scope)
    if op == "and":
        return bool(left) and bool(_eval(expr[3], scope))
    if op == "or":
        return bool(left) or bool(_eval(expr[3], scope))
    right = _eval(expr[3], scope)
    if op == "+":
        return left + right
    if op == "-":
        return left - right
    if op == "*":
        return left * right
    if op in ("/", "%"):
        # Integer division truncating toward zero, as in Kaitai (Java), DFDL and XQuery idiv/mod.
        quotient = abs(left) // abs(right) * (1 if (left < 0) == (right < 0) else -1)
        return quotient if op == "/" else left - right * quotient
    return {"=": left == right, "!=": left != right, "<": left < right,
            "<=": left <= right, ">": left > right, ">=": left >= right}[op]


class _Reader:
    def __init__(self, data: bytes, default_order: str):
        self.data = data
        self.pos = 0
        self.default_order = default_order
        self.last_delimiter = b""

    def take(self, n: int, what: str) -> bytes:
        if n < 0:
            raise ValueError(f"{what!r} has a negative length ({n})")
        if self.pos + n > len(self.data):
            raise ValueError(f"file ends at byte {len(self.data)}, before {what!r} "
                             f"({n} bytes at offset {self.pos})")
        chunk = self.data[self.pos:self.pos + n]
        self.pos += n
        return chunk

    def until(self, delimiters: List[bytes], what: str) -> bytes:
        """Text up to the first delimiter (consumed), or to the end of the data."""
        best = None
        for d in delimiters:
            i = self.data.find(d, self.pos)
            if i >= 0 and (best is None or i < best[0]):
                best = (i, d)
        if best is None:
            chunk = self.data[self.pos:]
            self.pos = len(self.data)
            self.last_delimiter = b""
            return chunk
        chunk = self.data[self.pos:best[0]]
        self.pos = best[0] + len(best[1])
        self.last_delimiter = best[1]
        return chunk

    def at_end(self) -> bool:
        return self.pos >= len(self.data)


def _semantic_attributes(desc: dict, value: Any = None) -> Dict[str, Any]:
    sem = desc.get("sem") or {}
    attrs = {key: sem.get(key) for key in ("semantic_name", "definition", "units", "units_uri", "concept_uri")}
    codes = sem.get("codes") or {}
    if value is not None and codes:
        key = _plain(value)
        attrs["meaning"] = codes.get(key)
    if value is not None and ("scale" in sem or "offset" in sem) and isinstance(value, (int, float)):
        raw = Decimal(str(value))
        scaled = raw * Decimal(sem["scale"]) if "scale" in sem else raw
        attrs["physical_value"] = scaled + Decimal(sem["offset"]) if "offset" in sem else scaled
    if value is not None and sem.get("fill") is not None and _plain(value) == sem["fill"]:
        attrs["fill"] = True
    if value is not None and codes and attrs.get("meaning") is None and not attrs.get("fill"):
        attrs["unknown_code"] = True
    if ("min" in sem or "max" in sem) and isinstance(value, (int, float)) and not attrs.get("fill"):
        physical = attrs.get("physical_value", Decimal(str(value)))
        attrs["valid_min"], attrs["valid_max"] = sem.get("min"), sem.get("max")
        if ("min" in sem and physical < Decimal(sem["min"])) or ("max" in sem and physical > Decimal(sem["max"])):
            attrs["out_of_range"] = True
    return attrs


def _plain(value: Any) -> str:
    if isinstance(value, (int, float)):
        return format(Decimal(str(value)).normalize(), "f")
    return str(value).strip()


def _occurrences(desc: dict, reader: _Reader, scope: _Scope, end_check) -> int:
    occurs = desc.get("occurs")
    if occurs is None:
        return 1
    if occurs[0] == "optional":
        return 1 if _eval(occurs[1], scope) else 0
    if occurs[0] == "repeat":
        return int(_eval(occurs[1], scope))
    return -1  # until end


def _read_all(desc: dict, reader: _Reader, scope: _Scope, text: Optional[Tuple[bytes, bytes]], last: bool) -> List[DrbNode]:
    count = _occurrences(desc, reader, scope, reader.at_end)
    nodes = []
    if count < 0:
        while not reader.at_end():
            nodes.append(_read_one(desc, reader, scope, text, last))
    else:
        for _ in range(count):
            nodes.append(_read_one(desc, reader, scope, text, last))
    return nodes


def _read_one(desc: dict, reader: _Reader, scope: _Scope, text: Optional[Tuple[bytes, bytes]], last: bool,
              keep: bool = True) -> DrbNode:
    start = reader.pos
    kind = desc["kind"]
    if kind == "field":
        value = _read_field(desc, reader, scope, text, last)
        if desc.get("occurs") is None:
            scope.values[desc["name"]] = value
        attrs = {"offset": start, "length": reader.pos - start, "type": desc["type"]}
        attrs.update(_semantic_attributes(desc, value))
        node = _Node(desc["name"], value, None, attrs)
        # What writing back needs: the text exactly as read, and what ended it.
        node._read_value = value
        if text is not None:
            node._raw_text = reader.data[start:reader.pos - len(reader.last_delimiter)]
            node._delimiter = reader.last_delimiter
        return node
    if kind == "record":
        inner = _Scope(scope)
        if keep and desc.get("occurs") is None:
            scope.values[desc["name"]] = inner
        children = _read_record(desc, reader, inner)
        attrs = {"offset": start, "length": reader.pos - start}
        attrs.update(_semantic_attributes(desc))
        return _Node(desc["name"], None, children, attrs)
    key = _eval(desc["on"], scope)
    for branch_key, record in desc["branches"]:
        if branch_key == key or str(branch_key) == str(key):
            branch = _read_one(record, reader, scope, None, False, keep=False)
            attrs = {"offset": start, "length": reader.pos - start}
            attrs.update(_semantic_attributes(desc))
            return _Node(desc["name"], None, [branch], attrs)
    raise ValueError(f"{desc['name']!r}: no branch for the value {key!r}")


def _read_record(desc: dict, reader: _Reader, scope: _Scope) -> List[DrbNode]:
    text = None
    if desc.get("text"):
        text = (desc["text"][0].encode("ascii"), desc["text"][1].encode("ascii"))
    children = desc["children"]
    nodes = []
    for i, child in enumerate(children):
        nodes.extend(_read_all(child, reader, scope, text, i == len(children) - 1))
    return nodes


def _read_field(desc: dict, reader: _Reader, scope: _Scope, text: Optional[Tuple[bytes, bytes]], last: bool) -> Any:
    kind = desc["type"]
    if text is not None:
        raw = reader.until([text[1]] if last else [text[0]], desc["name"]).decode("ascii", errors="replace")
        if last and raw.endswith("\r"):
            raw = raw[:-1]
        if kind in _STRUCT:
            return float(raw) if kind.startswith("float") else int(raw)
        return raw
    if kind in _STRUCT:
        order = desc.get("order") or reader.default_order
        chunk = reader.take(_WIDTH[kind], desc["name"])
        return struct.unpack((">" if order == "big" else "<") + _STRUCT[kind], chunk)[0]
    length = int(_eval(desc["length"], scope))
    chunk = reader.take(length, desc["name"])
    return chunk.decode("ascii", errors="replace") if kind == "string" else bytes(chunk)


def _encode(root: "_FormatNode") -> bytes:
    """The decoded file written back from its nodes' values, by the same description."""
    out = bytearray()
    _write_record(DESCRIPTION["root"], root.children, out, _Scope(None), "/")
    return bytes(out)


def _write_record(desc: dict, nodes: List[DrbNode], out: bytearray, scope: _Scope, path: str) -> None:
    text = None
    if desc.get("text"):
        text = (desc["text"][0].encode("ascii"), desc["text"][1].encode("ascii"))
    children = desc["children"]
    i = 0
    for position, child in enumerate(children):
        taken = []
        while i < len(nodes) and nodes[i].name == child["name"]:
            taken.append(nodes[i])
            i += 1
        _check_count(child, len(taken), scope, path)
        for node in taken:
            _write_one(child, node, out, scope, text, position == len(children) - 1, path + child["name"])
    if i < len(nodes):
        raise ValueError(f"{path}{nodes[i].name} isn't where the description expects it")


def _check_count(desc: dict, count: int, scope: _Scope, path: str) -> None:
    occurs = desc.get("occurs")
    if occurs is None:
        expected = 1
    elif occurs[0] == "optional":
        expected = 1 if _eval(occurs[1], scope) else 0
    elif occurs[0] == "repeat":
        expected = int(_eval(occurs[1], scope))
    else:
        return
    if count != expected:
        raise ValueError(f"{path}{desc['name']}: the description says there should be {expected}, "
                         f"but there {'is' if count == 1 else 'are'} {count}")


def _write_one(desc: dict, node: DrbNode, out: bytearray, scope: _Scope, text: Optional[Tuple[bytes, bytes]],
               last: bool, path: str, keep: bool = True) -> None:
    kind = desc["kind"]
    if kind == "field":
        out += _encode_field(desc, node, scope, text, last, path)
        if desc.get("occurs") is None:
            scope.values[desc["name"]] = node.value
        return
    if kind == "record":
        inner = _Scope(scope)
        if keep and desc.get("occurs") is None:
            scope.values[desc["name"]] = inner
        _write_record(desc, node.children, out, inner, path + "/")
        return
    key = _eval(desc["on"], scope)
    branch = node.children[0]
    for branch_key, record in desc["branches"]:
        if record["name"] == branch.name:
            if not (branch_key == key or str(branch_key) == str(key)):
                raise ValueError(f"{path}: the value {key!r} selects another branch than {branch.name!r}")
            _write_one(record, branch, out, scope, None, False, path + "/" + branch.name, keep=False)
            return
    raise ValueError(f"{path}: {branch.name!r} isn't one of its branches")


def _encode_field(desc: dict, node: DrbNode, scope: _Scope, text: Optional[Tuple[bytes, bytes]], last: bool,
                  path: str) -> bytes:
    kind, value = desc["type"], node.value
    if text is not None:
        raw = getattr(node, "_raw_text", None)
        if raw is not None and value == getattr(node, "_read_value", None):
            body = raw
        else:
            body = (repr(value) if isinstance(value, float) else str(value)).encode("ascii")
            if raw is not None and raw.endswith(b"\r"):
                body += b"\r"
        delimiter = getattr(node, "_delimiter", None)
        return body + (delimiter if delimiter is not None else text[1] if last else text[0])
    if kind in _STRUCT:
        order = desc.get("order") or DESCRIPTION["order"]
        try:
            return struct.pack((">" if order == "big" else "<") + _STRUCT[kind], value)
        except struct.error as ex:
            raise ValueError(f"{path}: {value!r} doesn't fit a {kind} ({ex})") from ex
    data = value.encode("ascii") if kind == "string" else bytes(value)
    length = int(_eval(desc["length"], scope))
    if len(data) != length:
        raise ValueError(f"{path}: the value is {len(data)} bytes, but its length is {length}")
    return data


def _node_at(root: DrbNode, path: str) -> DrbNode:
    current = root
    for step in [s for s in path.strip().strip("/").split("/")]:
        match = re.fullmatch(r"([^\[\]]+)(?:\[(\d+)\])?", step.strip())
        if match is None:
            raise ValueError(f"'{step}' isn't a path step")
        name, index = match.group(1), int(match.group(2) or 1)
        named = [c for c in current.children if c.name == name]
        if len(named) < index:
            raise ValueError(f"There's no element {path}: "
                             + (f"nothing is called '{name}' there" if not named
                                else f"there {'is only 1' if len(named) == 1 else f'are only {len(named)}'} called '{name}'"))
        current = named[index - 1]
    return current


def _typed(node: DrbNode, text: str, path: str) -> Any:
    kind = node.attributes.get(("type", None))
    try:
        if kind in _STRUCT:
            return float(text) if kind.startswith("float") else int(text.strip())
        if kind == "bytes" and text.strip().startswith("0x"):
            return bytes.fromhex(text.strip()[2:])
        return text.encode("ascii") if kind == "bytes" else text
    except ValueError as ex:
        raise ValueError(f"{path}: {text!r} isn't a valid {kind}") from ex


def _write(node: DrbNode, changes: Optional[Dict[str, str]] = None, **kwargs) -> bytes:
    """The file written back by the same description, with changes (element path -> new value as text).
    Counts, conditions, choices and lengths must still agree with the values, or this refuses. Bytes
    after the described data aren't written. With an add-in, its restore() then undoes prepare()."""
    root = _format_node(node)
    previous = []
    try:
        for path, text in (changes or {}).items():
            target = _node_at(root, path)
            if target.children or target.attributes.get(("type", None)) is None:
                raise ValueError(f"{path} is a group of elements, not a value")
            previous.append((target, target.value))
            target.value = _typed(target, text, path)
        written = _encode(root)
    finally:
        for target, value in reversed(previous):
            target.value = value
    restore = _hook("restore")
    return restore(written) if restore is not None else written


_ADDIN: List[Any] = []


def _addin() -> Any:
    """The hand-written add-in module next to this one, or None if there isn't one."""
    if not _ADDIN:
        name = __name__ + ".addin"
        try:
            found = importlib.util.find_spec(name) is not None
        except (ImportError, ValueError):
            found = False
        _ADDIN.append(importlib.import_module(name) if found else None)
    return _ADDIN[0]


def _hook(name: str) -> Any:
    addin = _addin()
    return getattr(addin, name, None) if addin is not None else None


class _FormatNode(WrappedNode):
    """A whole file decoded against DESCRIPTION; its children are the root record's elements."""

    def __init__(self, base_node: DrbNode):
        super().__init__(base_node)
        with base_node.get_impl(io.BufferedIOBase) as stream:
            data = stream.read()
        self.original_bytes = bytes(data)
        prepare = _hook("prepare")
        if prepare is not None:
            data = prepare(self.original_bytes)
            if not isinstance(data, (bytes, bytearray)):
                raise ValueError("the add-in's prepare() must return bytes, not " + type(data).__name__)
        self.decoded_bytes = bytes(data)
        reader = _Reader(self.decoded_bytes, DESCRIPTION["order"])
        self._children = _read_record(DESCRIPTION["root"], reader, _Scope(None))
        for child in self._children:
            child.parent = self
        self.trailing_bytes = len(self.decoded_bytes) - reader.pos
        # Also when the factory is used directly, without drb's resolver attaching the add-ons.
        for addon in (SemanticsAddon, MetadataAddon, ChecksAddon, WriteAddon):
            self.add_impl(addon.return_type(), addon.KIND, addon.identifier())

    @property
    def children(self) -> List[DrbNode]:
        return self._children

    # WrappedNode passes these to the file node, which would lose the add-ons added to this one.
    def has_impl(self, impl: type, identifier: str = None) -> bool:
        return DrbNode.has_impl(self, impl, identifier) or super().has_impl(impl, identifier)

    def get_impl(self, impl: type, identifier: str = None, **kwargs) -> Any:
        if DrbNode.has_impl(self, impl, identifier):
            return DrbNode.get_impl(self, impl, identifier, **kwargs)
        return super().get_impl(impl, identifier, **kwargs)


def _format_node(node: DrbNode) -> "_FormatNode":
    return node if isinstance(node, _FormatNode) else _FormatNode(node)


def _leaves(node: DrbNode, path: str = ""):
    """(path, node) for every decoded value; repeated elements are numbered from 1, e.g. /sample[2]."""
    counts: Dict[str, int] = {}
    for child in node.children:
        counts[child.name] = counts.get(child.name, 0) + 1
    seen: Dict[str, int] = {}
    for child in node.children:
        seen[child.name] = seen.get(child.name, 0) + 1
        child_path = path + "/" + child.name + (f"[{seen[child.name]}]" if counts[child.name] > 1 else "")
        if child.children:
            yield from _leaves(child, child_path)
        else:
            yield child_path, child


def _attr(node: DrbNode, key: str) -> Any:
    return node.attributes.get((key, None))


def _shown(value: Any) -> Any:
    if isinstance(value, (bytes, bytearray)):
        return "0x" + bytes(value).hex()
    if isinstance(value, Decimal):
        return format(value.normalize(), "f")
    return value


def _semantics(node: DrbNode) -> List[Dict[str, Any]]:
    """Every decoded value with what it means: semantic name, definition, units, code meaning, physical value."""
    rows = []
    for path, leaf in _leaves(_format_node(node)):
        row = {"path": path, "name": leaf.name, "value": _shown(leaf.value)}
        for key in ("semantic_name", "definition", "units", "units_uri", "concept_uri", "meaning",
                    "physical_value", "fill", "valid_min", "valid_max"):
            if _attr(leaf, key) is not None:
                row[key] = _shown(_attr(leaf, key))
        rows.append(row)
    return rows


def _metadata(node: DrbNode) -> Dict[str, Any]:
    """Each value by its semantic name (else its element path) as meant: a code's meaning, a scaled value's
    physical value, None for a fill value, else the value itself. A name found more than once gives a
    list. The add-in's metadata(root), if any, is merged in."""
    root = _format_node(node)
    result: Dict[str, Any] = {}
    repeated = set()
    for path, leaf in _leaves(root):
        key = _attr(leaf, "semantic_name") or re.sub(r"\[\d+\]", "", path)
        if _attr(leaf, "fill"):
            value = None
        elif _attr(leaf, "meaning") is not None:
            value = _attr(leaf, "meaning")
        elif _attr(leaf, "physical_value") is not None:
            value = _shown(_attr(leaf, "physical_value"))
        else:
            value = _shown(leaf.value)
        if key not in result:
            result[key] = value
            continue
        if key not in repeated:
            result[key] = [result[key]]
            repeated.add(key)
        result[key].append(value)
    extra = _hook("metadata")
    if extra is not None:
        result.update(extra(root) or {})
    return result


def _checks(node: DrbNode) -> List[str]:
    """Problems found in a decoded file: values outside their valid range or code list, bytes the
    description doesn't cover, and whatever the add-in's check(root) reports. Empty if there are none."""
    root = _format_node(node)
    problems = []
    for path, leaf in _leaves(root):
        if _attr(leaf, "out_of_range"):
            low, high = _attr(leaf, "valid_min"), _attr(leaf, "valid_max")
            shown = _attr(leaf, "physical_value")
            problems.append(f"{path} = {_shown(leaf.value if shown is None else shown)} is outside its valid range "
                            f"({'...' if low is None else low} to {'...' if high is None else high})")
        if _attr(leaf, "unknown_code"):
            problems.append(f"{path} = {_shown(leaf.value)} isn't in its code list")
    if root.trailing_bytes > 0:
        problems.append(f"{root.trailing_bytes} bytes at the end aren't covered by the description")
    check = _hook("check")
    if check is not None:
        problems.extend(str(p) for p in (check(root) or []))
    return problems


class _GeneratedAddon(Addon):
    """A drb-python add-on for files of this driver's topic; ADDON_PREFIX and TOPIC_ID are set below."""
    KIND = None
    RETURNS = None

    @classmethod
    def identifier(cls) -> str:
        return ADDON_PREFIX + "_" + cls.__name__[:-len("Addon")].lower()

    @classmethod
    def return_type(cls) -> type:
        return cls.RETURNS

    def apply(self, node: DrbNode, **kwargs) -> Any:
        return type(self).KIND(node)

    def can_apply(self, source) -> bool:
        return str(getattr(source, "id", "")) == TOPIC_ID


class SemanticsAddon(_GeneratedAddon):
    """Every decoded value with its meaning (a list of dicts)."""
    KIND = staticmethod(_semantics)
    RETURNS = list


class MetadataAddon(_GeneratedAddon):
    """Semantic name -> value (a dict)."""
    KIND = staticmethod(_metadata)
    RETURNS = dict


class ChecksAddon(_GeneratedAddon):
    """Problems found (a list of str; empty if none)."""
    KIND = staticmethod(_checks)
    RETURNS = list


class WriteAddon(_GeneratedAddon):
    """The file written back (bytes), with changes={path: value}."""
    KIND = staticmethod(_write)
    RETURNS = bytes

    def apply(self, node: DrbNode, **kwargs) -> Any:
        return _write(node, **kwargs)
