"""
drb-python driver generated by archive-manager's RepInfo Tools.

The driver is this generic interpreter plus DESCRIPTION (below): the format's
engine-neutral description - records, fields, choices, repetition, computed
lengths and counts, delimited text - as plain data, walked at read time. No
part of the description is ever executed as Python code; expressions are
small trees evaluated by _eval.

Each decoded element becomes a DrbNode, in data order. Repeated elements are
same-named siblings; a choice is a node holding the chosen branch's record;
an optional element whose condition is false is simply absent. Every node's
attributes carry its byte "offset" and "length", and its semantics
("semantic_name", "definition", "units", "units_uri", "concept_uri"); a coded
value also gets its "meaning", and a scaled value its "physical_value".
See the package's README.md for installing and using it.
"""
import io
import struct
from decimal import Decimal
from typing import Any, Dict, List, Optional, Tuple

from drb.core import DrbFactory, DrbNode
from drb.exceptions.core import DrbFactoryException
from drb.nodes.abstract_node import AbstractNode
from drb.nodes.logical_node import WrappedNode

_STRUCT = {"int8": "b", "uint8": "B", "int16": "h", "uint16": "H",
           "int32": "i", "uint32": "I", "int64": "q", "uint64": "Q",
           "float32": "f", "float64": "d"}
_WIDTH = {"int8": 1, "uint8": 1, "int16": 2, "uint16": 2, "int32": 4, "uint32": 4,
          "int64": 8, "uint64": 8, "float32": 4, "float64": 8}


class _Node(AbstractNode):
    """One decoded element: a value (field) or a group of nodes (record, choice)."""

    def __init__(self, name: str, value: Any, children: Optional[List[DrbNode]], attributes: Dict[str, Any]):
        super().__init__()
        self.name = name
        self.value = value
        self._children = children if children is not None else []
        for child in self._children:
            child.parent = self
        self._attrs = {(key, None): val for key, val in attributes.items() if val is not None}

    @property
    def attributes(self) -> Dict[Tuple[str, str], Any]:
        return self._attrs

    @property
    def children(self) -> List[DrbNode]:
        return self._children

    def __setitem__(self, key, value):
        raise NotImplementedError

    def __delitem__(self, key):
        raise NotImplementedError


class _Scope:
    """Values of fields read so far, looked up nearest record first - the same
    rule the description's expressions were validated against."""

    def __init__(self, parent: Optional["_Scope"]):
        self.parent = parent
        self.values: Dict[str, Any] = {}

    def lookup(self, name: str) -> Any:
        scope = self
        while scope is not None:
            if name in scope.values:
                return scope.values[name]
            scope = scope.parent
        raise ValueError(f"no value for {name!r} yet")


def _eval(expr: list, scope: _Scope) -> Any:
    kind = expr[0]
    if kind in ("int", "str"):
        return expr[1]
    if kind == "ref":
        return scope.lookup(expr[1])
    if kind == "neg":
        return -_eval(expr[1], scope)
    if kind == "not":
        return not _eval(expr[1], scope)
    op, left = expr[1], _eval(expr[2], scope)
    if op == "and":
        return bool(left) and bool(_eval(expr[3], scope))
    if op == "or":
        return bool(left) or bool(_eval(expr[3], scope))
    right = _eval(expr[3], scope)
    if op == "+":
        return left + right
    if op == "-":
        return left - right
    if op == "*":
        return left * right
    if op in ("/", "%"):
        # Integer division truncating toward zero, as in Kaitai (Java), DFDL and XQuery idiv/mod.
        quotient = abs(left) // abs(right) * (1 if (left < 0) == (right < 0) else -1)
        return quotient if op == "/" else left - right * quotient
    return {"=": left == right, "!=": left != right, "<": left < right,
            "<=": left <= right, ">": left > right, ">=": left >= right}[op]


class _Reader:
    def __init__(self, data: bytes, default_order: str):
        self.data = data
        self.pos = 0
        self.default_order = default_order

    def take(self, n: int, what: str) -> bytes:
        if n < 0:
            raise ValueError(f"{what!r} has a negative length ({n})")
        if self.pos + n > len(self.data):
            raise ValueError(f"file ends at byte {len(self.data)}, before {what!r} "
                             f"({n} bytes at offset {self.pos})")
        chunk = self.data[self.pos:self.pos + n]
        self.pos += n
        return chunk

    def until(self, delimiters: List[bytes], what: str) -> bytes:
        """Text up to the first delimiter (consumed), or to the end of the data."""
        best = None
        for d in delimiters:
            i = self.data.find(d, self.pos)
            if i >= 0 and (best is None or i < best[0]):
                best = (i, d)
        if best is None:
            chunk = self.data[self.pos:]
            self.pos = len(self.data)
            return chunk
        chunk = self.data[self.pos:best[0]]
        self.pos = best[0] + len(best[1])
        return chunk

    def at_end(self) -> bool:
        return self.pos >= len(self.data)


def _semantic_attributes(desc: dict, value: Any = None) -> Dict[str, Any]:
    sem = desc.get("sem") or {}
    attrs = {key: sem.get(key) for key in ("semantic_name", "definition", "units", "units_uri", "concept_uri")}
    codes = sem.get("codes") or {}
    if value is not None and codes:
        key = _plain(value)
        attrs["meaning"] = codes.get(key)
    if value is not None and ("scale" in sem or "offset" in sem) and isinstance(value, (int, float)):
        raw = Decimal(str(value))
        scaled = raw * Decimal(sem["scale"]) if "scale" in sem else raw
        attrs["physical_value"] = scaled + Decimal(sem["offset"]) if "offset" in sem else scaled
    if value is not None and sem.get("fill") is not None and _plain(value) == sem["fill"]:
        attrs["fill"] = True
    return attrs


def _plain(value: Any) -> str:
    if isinstance(value, (int, float)):
        return format(Decimal(str(value)).normalize(), "f")
    return str(value).strip()


def _occurrences(desc: dict, reader: _Reader, scope: _Scope, end_check) -> int:
    occurs = desc.get("occurs")
    if occurs is None:
        return 1
    if occurs[0] == "optional":
        return 1 if _eval(occurs[1], scope) else 0
    if occurs[0] == "repeat":
        return int(_eval(occurs[1], scope))
    return -1  # until end


def _read_all(desc: dict, reader: _Reader, scope: _Scope, text: Optional[Tuple[bytes, bytes]], last: bool) -> List[DrbNode]:
    count = _occurrences(desc, reader, scope, reader.at_end)
    nodes = []
    if count < 0:
        while not reader.at_end():
            nodes.append(_read_one(desc, reader, scope, text, last))
    else:
        for _ in range(count):
            nodes.append(_read_one(desc, reader, scope, text, last))
    return nodes


def _read_one(desc: dict, reader: _Reader, scope: _Scope, text: Optional[Tuple[bytes, bytes]], last: bool) -> DrbNode:
    start = reader.pos
    kind = desc["kind"]
    if kind == "field":
        value = _read_field(desc, reader, scope, text, last)
        if desc.get("occurs") is None:
            scope.values[desc["name"]] = value
        attrs = {"offset": start, "length": reader.pos - start, "type": desc["type"]}
        attrs.update(_semantic_attributes(desc, value))
        return _Node(desc["name"], value, None, attrs)
    if kind == "record":
        children = _read_record(desc, reader, _Scope(scope))
        attrs = {"offset": start, "length": reader.pos - start}
        attrs.update(_semantic_attributes(desc))
        return _Node(desc["name"], None, children, attrs)
    key = _eval(desc["on"], scope)
    for branch_key, record in desc["branches"]:
        if branch_key == key or str(branch_key) == str(key):
            branch = _read_one(record, reader, scope, None, False)
            attrs = {"offset": start, "length": reader.pos - start}
            attrs.update(_semantic_attributes(desc))
            return _Node(desc["name"], None, [branch], attrs)
    raise ValueError(f"{desc['name']!r}: no branch for the value {key!r}")


def _read_record(desc: dict, reader: _Reader, scope: _Scope) -> List[DrbNode]:
    text = None
    if desc.get("text"):
        text = (desc["text"][0].encode("ascii"), desc["text"][1].encode("ascii"))
    children = desc["children"]
    nodes = []
    for i, child in enumerate(children):
        nodes.extend(_read_all(child, reader, scope, text, i == len(children) - 1))
    return nodes


def _read_field(desc: dict, reader: _Reader, scope: _Scope, text: Optional[Tuple[bytes, bytes]], last: bool) -> Any:
    kind = desc["type"]
    if text is not None:
        raw = reader.until([text[1]] if last else [text[0]], desc["name"]).decode("ascii", errors="replace")
        if last and raw.endswith("\r"):
            raw = raw[:-1]
        if kind in _STRUCT:
            return float(raw) if kind.startswith("float") else int(raw)
        return raw
    if kind in _STRUCT:
        order = desc.get("order") or reader.default_order
        chunk = reader.take(_WIDTH[kind], desc["name"])
        return struct.unpack((">" if order == "big" else "<") + _STRUCT[kind], chunk)[0]
    length = int(_eval(desc["length"], scope))
    chunk = reader.take(length, desc["name"])
    return chunk.decode("ascii", errors="replace") if kind == "string" else bytes(chunk)


class _FormatNode(WrappedNode):
    """A whole file decoded against DESCRIPTION; its children are the root record's elements."""

    def __init__(self, base_node: DrbNode):
        super().__init__(base_node)
        with base_node.get_impl(io.BufferedIOBase) as stream:
            data = stream.read()
        reader = _Reader(data, DESCRIPTION["order"])
        self._children = _read_record(DESCRIPTION["root"], reader, _Scope(None))
        for child in self._children:
            child.parent = self
        self.trailing_bytes = len(data) - reader.pos

    @property
    def children(self) -> List[DrbNode]:
        return self._children
