package info.oais.infomodel.structure.kaitai;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.nio.BufferOverflowException;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.HexFormat;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kaitai.struct.ByteBufferKaitaiStream;
import io.kaitai.struct.ConsistencyError;
import io.kaitai.struct.KaitaiStream;
import io.kaitai.struct.KaitaiStruct;

import info.oais.infomodel.structure.ElementPath;
import info.oais.infomodel.structure.StructureInterpretationException;

/**
 * Writes data back with a class generated by {@code ksc --read-write}
 * ({@code -w}): Kaitai Struct's own serialization. Reads the data, fetches
 * the lazily read instances, sets the changed values through the generated
 * setters, has each changed object check itself ({@code _check()}, which
 * refuses e.g. a repeat count that no longer matches its list), and writes
 * everything to a new stream ({@code _write}).
 *
 * <p>Path steps name fields as in the description ({@code sample_count}) or
 * as the generated accessor does ({@code sampleCount}); an index picks an
 * element of a repeated field.</p>
 */
final class KaitaiWriter {

	private KaitaiWriter() {
	}

	static byte[] write(Class<? extends KaitaiStruct> type, byte[] original, Map<ElementPath, String> changes) {
		if (!KaitaiStruct.ReadWrite.class.isAssignableFrom(type)) {
			throw new StructureInterpretationException("Kaitai Struct class " + type.getName()
					+ " was compiled read-only; compile the .ksy with ksc --read-write (-w) to write data back");
		}
		try {
			// Kaitai writes into a stream of a fixed size, and an element repeated (or sized) to the end
			// of the data has to end exactly where the stream does. Start from the data's own size; if
			// that's too small, grow it, and if Kaitai reports bytes left over at such an element, shrink
			// it by that much.
			long size = original.length;
			for (int attempt = 0;; attempt++) {
				KaitaiStruct.ReadWrite root = readWithChanges(type, original, changes);
				TrackingStream out = new TrackingStream(size);
				try {
					root._write(out);
					return out.written();
				} catch (BufferOverflowException e) {
					if (attempt >= MAX_ATTEMPTS) {
						throw failure(e);
					}
					size = size * 2 + 1024;
				} catch (ConsistencyError e) {
					if (attempt >= MAX_ATTEMPTS || !Long.valueOf(0).equals(number(e.expected()))
							|| number(e.actual()) == null || number(e.actual()) <= 0 || number(e.actual()) > size) {
						throw failure(e);
					}
					size -= number(e.actual());
				}
			}
		} catch (InvocationTargetException e) {
			throw failure(e.getCause() != null ? e.getCause() : e);
		} catch (StructureInterpretationException e) {
			throw e;
		} catch (ReflectiveOperationException | RuntimeException e) {
			throw failure(e);
		}
	}

	private static final int MAX_ATTEMPTS = 12;

	/** Reads the data, fetches the lazy instances, applies the changes and has each changed object check itself. */
	private static KaitaiStruct.ReadWrite readWithChanges(Class<? extends KaitaiStruct> type, byte[] original,
			Map<ElementPath, String> changes) throws ReflectiveOperationException {
		KaitaiStruct.ReadWrite root = (KaitaiStruct.ReadWrite) type.getConstructor(KaitaiStream.class)
				.newInstance(new ByteBufferKaitaiStream(original));
		root._read();
		root._fetchInstances();
		Set<KaitaiStruct.ReadWrite> changed = new LinkedHashSet<>();
		for (Map.Entry<ElementPath, String> change : changes.entrySet()) {
			changed.add(set(root, change.getKey(), change.getValue()));
		}
		for (KaitaiStruct.ReadWrite struct : changed) {
			struct._check();
		}
		return root;
	}

	private static Long number(Object value) {
		return value instanceof Number n ? n.longValue() : null;
	}

	private static StructureInterpretationException failure(Throwable e) {
		String message = e.getMessage() != null ? e.getMessage() : e.toString();
		return new StructureInterpretationException("Kaitai Struct couldn't write the data back: " + message, e);
	}

	/** Sets the value at {@code path}; returns the object holding it, which has to check itself. */
	private static KaitaiStruct.ReadWrite set(KaitaiStruct.ReadWrite root, ElementPath path, String text)
			throws ReflectiveOperationException {
		Object current = root;
		List<ElementPath.Step> steps = path.steps();
		for (int i = 0; i < steps.size(); i++) {
			ElementPath.Step step = steps.get(i);
			if (!(current instanceof KaitaiStruct.ReadWrite struct)) {
				throw new StructureInterpretationException(path + ": '" + steps.get(i - 1).name()
						+ "' is a value, not a group of elements");
			}
			Method accessor = accessor(struct.getClass(), step.name());
			if (accessor == null) {
				throw new StructureInterpretationException(path.notFound(step, 0));
			}
			Object value = accessor.invoke(struct);
			boolean last = i == steps.size() - 1;
			if (value instanceof List<?> list) {
				if (list.size() < step.index()) {
					throw new StructureInterpretationException(path.notFound(step, list.size()));
				}
				if (last) {
					Object element = list.get(step.index() - 1);
					@SuppressWarnings("unchecked")
					List<Object> elements = (List<Object>) list;
					elements.set(step.index() - 1, convert(path, text, element == null ? String.class : element.getClass()));
					return struct;
				}
				current = list.get(step.index() - 1);
			} else {
				if (step.index() != 1) {
					throw new StructureInterpretationException(path.notFound(step, 1));
				}
				if (last) {
					if (value instanceof KaitaiStruct) {
						throw new StructureInterpretationException(path + " is a group of elements, not a value");
					}
					Method setter = setter(struct.getClass(), accessor.getName());
					if (setter == null) {
						throw new StructureInterpretationException(path + " is computed, so it can't be set");
					}
					setter.invoke(struct, convert(path, text, setter.getParameterTypes()[0]));
					return struct;
				}
				current = value;
			}
		}
		throw new IllegalStateException("unreachable");
	}

	private static Method accessor(Class<?> type, String name) {
		String camel = camelCase(name);
		return KaitaiReflectiveStructureNode.fieldAccessors(type)
				.filter(m -> m.getName().equals(name) || m.getName().equals(camel))
				.findFirst().orElse(null);
	}

	private static Method setter(Class<?> type, String accessor) {
		String name = "set" + Character.toUpperCase(accessor.charAt(0)) + accessor.substring(1);
		for (Method m : type.getMethods()) {
			if (m.getName().equals(name) && m.getParameterCount() == 1) {
				return m;
			}
		}
		return null;
	}

	/** Kaitai's Java names: {@code sample_count} becomes {@code sampleCount}. */
	static String camelCase(String name) {
		StringBuilder sb = new StringBuilder();
		boolean upper = false;
		for (char c : name.toCharArray()) {
			if (c == '_') {
				upper = sb.length() > 0;
			} else {
				sb.append(upper ? Character.toUpperCase(c) : c);
				upper = false;
			}
		}
		return sb.toString();
	}

	private static Object convert(ElementPath path, String text, Class<?> type) {
		String s = text.strip();
		try {
			if (type == String.class) {
				return text;
			}
			if (type == byte[].class) {
				return s.startsWith("0x") ? HexFormat.of().parseHex(s.substring(2)) : text.getBytes(StandardCharsets.UTF_8);
			}
			if (type == long.class || type == Long.class) {
				return Long.parseLong(s);
			}
			if (type == int.class || type == Integer.class) {
				return Integer.parseInt(s);
			}
			if (type == short.class || type == Short.class) {
				return Short.parseShort(s);
			}
			if (type == byte.class || type == Byte.class) {
				return Byte.parseByte(s);
			}
			if (type == double.class || type == Double.class) {
				return Double.parseDouble(s);
			}
			if (type == float.class || type == Float.class) {
				return Float.parseFloat(s);
			}
			if (type == boolean.class || type == Boolean.class) {
				return s.equals("1") || s.equalsIgnoreCase("true");
			}
		} catch (IllegalArgumentException e) {
			throw new StructureInterpretationException(path + ": '" + text + "' isn't a valid " + type.getSimpleName());
		}
		throw new StructureInterpretationException(path + " holds a " + type.getSimpleName() + ", which can't be set here");
	}

	/**
	 * A stream that remembers how far it was written: Kaitai seeks away to
	 * write elements at an offset and back again, so the end of the data is
	 * the furthest position reached, not where the stream finishes.
	 */
	private static final class TrackingStream extends ByteBufferKaitaiStream {
		private long furthest;

		TrackingStream(long size) {
			super(size);
		}

		@Override
		public void seek(long newPos) {
			furthest = Math.max(furthest, pos());
			super.seek(newPos);
		}

		@Override
		public void seek(int newPos) {
			furthest = Math.max(furthest, pos());
			super.seek(newPos);
		}

		byte[] written() {
			int length = (int) Math.max(furthest, pos());
			ByteBuffer buffer = asRoBuffer();
			buffer.position(0);
			byte[] bytes = new byte[length];
			buffer.get(bytes);
			return bytes;
		}
	}
}
